
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: nginx
      volumeMounts:
        # a mount for site-data
        - name: config
          mountPath: /usr/share/nginx/htmls
          subPath: html
        # another mount for nginx config
        - name: config
          mountPath: /etc/nginx/test.conf
          subPath: nginx.conf
  volumes:
    - name: config
      persistentVolumeClaim:
        claimName: test-nfs-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-nfs-claim
spec:
  storageClassName: hostpath 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi