apiVersion: v1
kind: Pod
metadata:
  name: envfrom-secret
spec:
  containers:
  - name: envars-test-container
    image: nginx
    envFrom:
    - secretRef:
        name: dotfile-secret-from
---
apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret-from
data:
  EBOO: dmFsdWUtMg0KDQo=
  yann: dmFsdWUtMg0KDQo=