apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret-string
stringData:
  .secret-file: anael
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-dotfiles-pod-string
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret-string
  containers:
    - name: dotfile-test-container
      image: nginx
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"